"""oilpumps

Revision ID: 360d611eaab9
Revises: 
Create Date: 2023-04-11 13:39:27.363389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360d611eaab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Oil_Pumps',
        sa.Column('id', sa.Integer(),  nullable=False),
        sa.Column('pressure', sa.Integer(), nullable=False),
        sa.Column('temperature', sa.Integer(), nullable=False),
        sa.Column('speed', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Oil_Pumps')
    # ### end Alembic commands ###
